# Generated by Django 6.0.7 on 2026-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dev_contribution',
            field=models.TextField(default='Website design, frontend, backend, database, deployment'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dev_features',
            field=models.TextField(default='Dynamic Content Management, Admin Panel Integration, Secure Form Handling'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dev_github',
            field=models.URLField(blank=True, default='https://github.com/elightphantom', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dev_purpose',
            field=models.TextField(default='To provide a premium, fast, and fully dynamic platform for the NGO.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dev_role',
            field=models.CharField(default='Full-Stack Developer / Web Developer', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dev_security',
            field=models.TextField(default='CSRF Protection, XSS/SQL Injection Prevention, Optimized Media Delivery'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dev_technologies',
            field=models.TextField(default='HTML, CSS, JavaScript, Python/Django, SQLite'),
        ),
    ]
