# Generated by Django 6.0.7 on 2026-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_contribution',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_features',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_github',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_purpose',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_role',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_security',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dev_technologies',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='developer_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='features_developed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purpose_of_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Full-Stack Developer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
